language: ruby
rvm:
- 2.3.3

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec jekyll build

sudo: false # route your build to the container-based infrastructure for a faster build
