# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nipkow
email: ettingshausen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Stay Hungry, Stay Foolish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nipkow.lofter.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  ettingshausen
instagram_username:  ettingshausen
google_analytics: UA-102246716-1

# Build settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
# highlighter: rouge
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-pwa-plugin


pwa:
  sw_filename: service-worker.js # Required
  dest_js_directory: assets/js # Required
  cache_name: my-cache # Optional
  precache_channel_name: sw-precache # Optional
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"
  runtime_cache: # Optional
    - route: /^api\/getdata/
      strategy: networkFirst
    - route: "'/api/pic'"
      strategy: cacheFirst  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
